# Generated by Django 4.2.11 on 2024-04-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='../mm-post-defult_ysbgha', upload_to='images/'),
        ),
    ]
